AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t3.small
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  ImageId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64 # Amazon Linux 2023

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref 'ImageId'
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      # SourceDestCheck: false <---- Do not uncomment this line or it will get failed.
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref 'Eth0'
        DeviceIndex: '0'
      - NetworkInterfaceId: !Ref 'Eth1'
        DeviceIndex: '1'

  Eth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: eth0
      GroupSet: [!Ref 'SecurityGroupId']
      SubnetId: !Ref 'SubnetId'
      SourceDestCheck: false

  Eth1:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: eth1
      GroupSet: [!Ref 'SecurityGroupId']
      SubnetId: !Ref 'SubnetId'
      SourceDestCheck: false
